### ISSUE TITLE
TypeError: 'FlowMod' object is not iterable - Main.on_openflow_connection_error

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/flow_manager#131]
Hi,

The scenario was basically the creation of multiple EVCs which made the kytos server be overloaded, switches started disconnecting because OpenFlow hello were not received and then this error started happening:

```
Jan 26 17:26:36 886ed6e01833 kytos.core.helpers:ERROR helpers:151:  listen_to handler: <function Main.on_openflow_connection_error at 0x7fa49d5cda60>, args: (<Main(flow_manager, stopped 140342661728000)>, KytosEvent('kytos/core.openflow.connection.error', {'destination': Connection('127.0.0.1', 43712, <asyncio.TransportSocket fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>, Switch('00:00:00:00:00:00:00:22'), <ConnectionState.FINISHED: 4>), 'message': FlowMod(xid=1304559762), 'exception': 'Connection state: ConnectionState.FINISHED'}, 1000)) traceback: Traceback (most recent call last):,   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 313, in _retry_on_openflow_connection_error,     self._send_flow_mod(flow.switch, flow_mod),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 731, in _send_flow_mod,     raise SwitchNotConnectedError(, napps.kytos.flow_manager.exceptions.SwitchNotConnectedError: switch 00:00:00:00:00:00:00:22 isn't connected, , During handling of the above exception, another exception occurred:, , Traceback (most recent call last):,   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 313, in _retry_on_openflow_connection_error,     self._send_flow_mod(flow.switch, flow_mod),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 731, in _send_flow_mod,     raise SwitchNotConnectedError(, napps.kytos.flow_manager.exceptions.SwitchNotConnectedError: switch 00:00:00:00:00:00:00:22 isn't connected, , During handling of the above exception, another exception occurred:, , Traceback (most recent call last):,   File "/usr/local/lib/python3.9/dist-packages/kytos/core/helpers.py", line 146, in handler_context_apm,     result = handler(*args),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 767, in on_openflow_connection_error,     self._retry_on_openflow_connection_error(event),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 319, in _retry_on_openflow_connection_error,     return self._retry_on_openflow_connection_error(event, xid),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 319, in _retry_on_openflow_connection_error,     return self._retry_on_openflow_connection_error(event, xid),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 315, in _retry_on_openflow_connection_error,     self._send_barrier_request(flow.switch, flow_mod),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 719, in _send_barrier_request,     self._add_barrier_request(switch.id, barrier_xid, flow_mods),   File "//var/lib/kytos/napps/kytos/flow_manager/main.py", line 705, in _add_barrier_request,     self._pending_barrier_reply[dpid][barrier_xid] = [, TypeError: 'FlowMod' object is not iterable,
```

**Comment by viniarck** [comment]
Hi @italovalcy, thanks for catching this. 

Let's also include to be patched on `2022.3.1` since I'm already fixing other things on `flow_manager`, this is a traceback that can impact error handling and OpenFlow connection socket errors can happen.
