### ISSUE TITLE
FlowMod raises an Internal Server Error if switch is not connected and flows are not persisted

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/flow_manager#26]
When we request a FlowMod to install, update or remove Flows, flow_manager will raise an Internal Server Error and the requested flows will not be persisted.

Usually, that happens because of the of_core's FlowFactory (https://github.com/kytos-ng/flow_manager/blob/master/main.py#L445):
```
2021-10-26 15:03:14,444 - ERROR [kytos.core.controller] (Thread-60937) Exception on /api/kytos/flow_manager/v2/delete/00:00:00:00:00:00:00:04 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/kytos/napps/kytos/flow_manager/main.py", line 404, in delete
    return self._send_flow_mods_from_request(dpid, "delete")
  File "/var/lib/kytos/napps/kytos/flow_manager/main.py", line 444, in _send_flow_mods_from_request
    self._install_flows(command, flows_dict, [switch])
  File "/var/lib/kytos/napps/kytos/flow_manager/main.py", line 464, in _install_flows
    flow = serializer.from_dict(flow_dict, switch)
AttributeError: 'NoneType' object has no attribute 'from_dict'

2021-10-26 15:04:20,812 - ERROR [kytos.core.controller] (Thread-61857) Exception on /api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:02 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/kytos/napps/kytos/flow_manager/main.py", line 393, in add
    return self._send_flow_mods_from_request(dpid, "add")
  File "/var/lib/kytos/napps/kytos/flow_manager/main.py", line 444, in _send_flow_mods_from_request
    self._install_flows(command, flows_dict, [switch])
  File "/var/lib/kytos/napps/kytos/flow_manager/main.py", line 464, in _install_flows
    flow = serializer.from_dict(flow_dict, switch)
AttributeError: 'NoneType' object has no attribute 'from_dict'
```

Another side effect is the flow request are not saved.

My suggestion is that: 1) we handle the exception and return the specific error for the requester (maybe using `werkzeug.exceptions.FailedDependency ` with a reasonable description of the failure); 2) adds an extra option `force` that would persist the request (to be sent to the switches later by the consistency routine).

**Comment by viniarck** [comment]
I discussed with Italo to split this in two parts, the second one will be addressed on issue #46. On this issue 26, we'll ship this first requirement: 

`1) we handle the exception and return the specific error for the requester (maybe using werkzeug.exceptions.FailedDependency with a reasonable description of the failure);`
